### ISSUE TITLE
Creating Dashboard

### ISSUE THREAD

**Issue by Saurabhdimri06** [USoC2020/Retail_sales_prediction#21]
## Dashboard layout

- In this segment, we will work on creating a User Interface of the dashboard.
- The skeleton of the dashboard should be made, along with the redirect pages and URLs, so that we may get the look and feel of the dashboard where the details of the ML prediction will be plotted later on

## Suggestions

- It is suggested that on the dashboard there must be some data parsing as from the backend. So that the dashboard is more dynamic and hence then dummy data can be replaced afterwards

**Comment by priyansh19** [comment]
If you have any issue you can ask on slack
